@startuml
class GerenciarCategoria
class GerenciarCliente
class GerenciarPedido
class GerenciarProduto
class GerenciarUsuario
class Login
class Menu
class bancoDeDados.ProvedorConexao
class bancoDeDados.UtilidadeInventario
class bancoDeDados.tables
class com.itextpdf.text.BaseColor
class com.itextpdf.text.Paragraph
class com.itextpdf.text.Phrase
class com.itextpdf.text.pdf.PdfPCell
class com.itextpdf.text.pdf.PdfPTable
class com.itextpdf.text.pdf.PdfWriter
class common.abrirPDF
class java.awt.Color
class java.io.File
class java.io.FileOutputStream
class java.text.SimpleDateFormat
class java.util.Calendar
class javax.swing.JFrame
class javax.swing.JOptionPane
class javax.swing.table.DefaultTableModel
class javax.swing.table.TableModel
class verPedido
GerenciarCategoria ..> bancoDeDados.ProvedorConexao
GerenciarCategoria --|> javax.swing.JFrame
GerenciarCategoria ..> javax.swing.JOptionPane
GerenciarCategoria ..> javax.swing.table.DefaultTableModel
GerenciarCategoria ..> javax.swing.table.TableModel
GerenciarCliente ..> bancoDeDados.ProvedorConexao
GerenciarCliente --|> javax.swing.JFrame
GerenciarCliente ..> javax.swing.JOptionPane
GerenciarCliente ..> javax.swing.table.DefaultTableModel
GerenciarCliente ..> javax.swing.table.TableModel
GerenciarPedido ..> bancoDeDados.ProvedorConexao
GerenciarPedido ..> bancoDeDados.UtilidadeInventario
GerenciarPedido ..> com.itextpdf.text.BaseColor
GerenciarPedido ..> com.itextpdf.text.Paragraph
GerenciarPedido ..> com.itextpdf.text.Phrase
GerenciarPedido ..> com.itextpdf.text.pdf.PdfPCell
GerenciarPedido ..> com.itextpdf.text.pdf.PdfPTable
GerenciarPedido ..> com.itextpdf.text.pdf.PdfWriter
GerenciarPedido ..> common.abrirPDF
GerenciarPedido ..> java.io.FileOutputStream
GerenciarPedido ..> java.text.SimpleDateFormat
GerenciarPedido ..> java.util.Calendar
GerenciarPedido --|> javax.swing.JFrame
GerenciarPedido ..> javax.swing.JOptionPane
GerenciarPedido ..> javax.swing.table.DefaultTableModel
GerenciarPedido ..> javax.swing.table.TableModel
GerenciarProduto ..> bancoDeDados.ProvedorConexao
GerenciarProduto --|> javax.swing.JFrame
GerenciarProduto ..> javax.swing.JOptionPane
GerenciarProduto ..> javax.swing.table.DefaultTableModel
GerenciarProduto ..> javax.swing.table.TableModel
GerenciarUsuario ..> bancoDeDados.ProvedorConexao
GerenciarUsuario ..> java.awt.Color
GerenciarUsuario --|> javax.swing.JFrame
GerenciarUsuario ..> javax.swing.JOptionPane
GerenciarUsuario ..> javax.swing.table.DefaultTableModel
GerenciarUsuario ..> javax.swing.table.TableModel
Login ..> bancoDeDados.ProvedorConexao
Login --|> javax.swing.JFrame
Menu --|> javax.swing.JFrame
Menu ..> javax.swing.JOptionPane
common.abrirPDF ..> bancoDeDados.UtilidadeInventario
common.abrirPDF ..> java.io.File
common.abrirPDF ..> javax.swing.JOptionPane
verPedido ..> bancoDeDados.ProvedorConexao
verPedido ..> common.abrirPDF
verPedido --|> javax.swing.JFrame
verPedido ..> javax.swing.JOptionPane
verPedido ..> javax.swing.table.DefaultTableModel
verPedido ..> javax.swing.table.TableModel
@enduml